models/property.py
from utils.db import db

class Property(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50), nullable=False)
    category = db.Column(db.String(50), nullable=False)
    city = db.Column(db.String(200), nullable=False)
    size = db.Column(db.String(200), nullable=False)
    clasification = db.Column(db.String(200), nullable=False)
    price = db.Column(db.Integer, nullable=False)
    details = db.Column(db.String(500), nullable=False)
    banos = db.Column(db.Integer, nullable=False)
    dormitorios = db.Column(db.Integer, nullable = False)
    parqueos = db.Column(db.Integer, nullable = False)
    fotoperfil = db.Column(db.String(1000), nullable = False)
    foto1 = db.Column(db.String(1000), nullable = False)
    foto2 = db.Column(db.String(1000), nullable = False)
    foto3 = db.Column(db.String(1000), nullable = False)
    foto4 = db.Column(db.String(1000), nullable = False)

    def __init__(self, name, category, city, size, clasification, price, details, banos, dormitorios, parqueos, fotoperfil, foto1, foto2, foto3, foto4) -> None:
        self.name = name
        self.category = category
        self.city = city
        self.size = size
        self.clasification = clasification
        self.price = price
        self.details = details
        self.banos = banos
        self.dormitorios = dormitorios
        self.parqueos = parqueos
        self.fotoperfil = fotoperfil
        self.foto1 = foto1
        self.foto2 = foto2
        self.foto3 = foto3
        self.foto4 = foto4

forms/loginForm.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import InputRequired, Length, ValidationError
from models.user import User


class LoginForm(FlaskForm):
    username = StringField(
        validators=[
            InputRequired(),
            Length(min=4, max=20),
        ],
        render_kw={"placeholder": "username"},
    )

    password = PasswordField(
        validators=[
            InputRequired(),
            Length(min=4, max=20),
        ],
        render_kw={"placeholder": "password"},
    )

    submit = SubmitField("login")

forms/registerForm.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import InputRequired, Length, ValidationError
from models.user import User


class RegisterForm(FlaskForm):
    username = StringField(
        validators=[
            InputRequired(),
            Length(min=4, max=20),
        ],
        render_kw={"placeholder": "username"},
    )

    password = PasswordField(
        validators=[
            InputRequired(),
            Length(min=4, max=20),
        ],
        render_kw={"placeholder": "password"},
    )

    submit = SubmitField("register")

    def validate_username(self, username):
        currentUser = User.query.filter_by(username=username).first()
        if currentUser:
            raise ValidationError("the username already exists")

routes/auth.py
from flask import Blueprint, render_template, redirect, url_for
from flask_login import login_user, login_required, logout_user, current_user
from forms.registerForm import RegisterForm
from forms.loginForm import LoginForm
from utils.bcryptService import bcrypt
from models.user import User
from utils.db import db

auth = Blueprint("auth", __name__)

@auth.route("/login", methods=["GET", "POST"])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data
        currentUser = User.query.filter_by(username=username).first()
        if currentUser:
            if bcrypt.check_password_hash(currentUser.password, password):
                login_user(currentUser)
                return redirect(url_for("dashboard.home"))
    return render_template("login.html", form=form)

@auth.route("/register", methods=["GET", "POST"])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data
        hashed_password = bcrypt.generate_password_hash(password)
        newUser = User(username, hashed_password, "active", "user")
        db.session.add(newUser)
        db.session.commit()
        return redirect(url_for("auth.login"))
    return render_template("register.html", form=form)


@auth.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("auth.login"))


@auth.route("/dashboard")
@login_required
def dashboard():
    print(f"current_user: {current_user}")
    return render_template("dashboard.html", user=current_user)

routes/contacto.py
from flask import Blueprint, render_template, redirect, url_for
from utils.db import db
from forms.createMessage import createMessageForm
from models.message import Message

contact = Blueprint("contacto", __name__)


@contact.route("/contacto", methods=["GET", "POST"])
def contacto():
    form = createMessageForm()
    if form.validate_on_submit():
        name = form.name.data
        mail = form.mail.data
        message = form.message.data
        newMessage = Message(name, mail, message)
        db.session.add(newMessage)
        db.session.commit()
        return redirect(url_for("contacto.contacto"))
    return render_template("contacto.html", form = form)

routes/dashboard.py
from flask import Blueprint, render_template, redirect, url_for
from flask_login import login_user, login_required, current_user
from utils.db import db
from forms.createMessage import createMessageForm
from forms.createProperty import createPropertyForm
from models.property import Property
from models.message import Message
from models.user import User

dashboard = Blueprint("dashboard", __name__)

@dashboard.route("/dashboard", methods=["GET", "POST"])
@login_required
def home():
    MessageList = Message.query.all()
    PropertyList = Property.query.all()
    if "admin" in current_user.rank:
        return render_template("dashboard.html", MessageList = MessageList, PropertyList = PropertyList)
    else:
        return redirect(url_for("home.home"))
    
       
@dashboard.route("/Propiedades", methods=["GET", "POST"])
@login_required
def property():
    form = createPropertyForm()
    if form.validate_on_submit():
        name = form.name.data
        category = form.category.data
        city = form.city.data
        size = form.size.data
        clasification = form.clasification.data
        price = form.price.data
        details = form.details.data
        banos = form.banos.data
        dormitorios = form.dormitorios.data
        parqueos = form.parqueos.data
        fotoperfil = form.fotoperfil.data
        foto1 = form.foto1.data
        foto2 = form.foto2.data
        foto3 = form.foto3.data
        foto4 = form.foto4.data
        newProperty = Property(name, category, city, size, clasification, price,
                               details, banos, dormitorios, parqueos, fotoperfil, foto1, foto2, foto3, foto4)
        db.session.add(newProperty)
        db.session.commit()
    form.name.data = ""
    form.category.data = ""
    form.city.data = ""
    form.size.data = ""
    form.clasification.data = ""
    form.price.data = ""
    form.details.data = ""
    form.banos.data = ""
    form.dormitorios.data = ""
    form.parqueos.data = ""
    form.fotoperfil.data = ""
    form.foto1.data = ""
    form.foto2.data = ""
    form.foto3.data = ""
    form.foto4.data = ""

    if "admin" in current_user.rank:
        return render_template("property.html", form = form)
    else:
        return redirect(url_for("home.home"))

routes/home.py
from flask import Blueprint, render_template
from utils.db import db
from models.property import Property

house = Blueprint("home", __name__)


@house.route("/", methods=["GET", "POST"])
def home():
    PropertyList = Property.query.all()
    ListCasas = Property.query.filter_by(clasification="Casa").all()
    ListApartamentos = Property.query.filter_by(clasification="Apartamento").first()
    ListRanchos = Property.query.filter_by(clasification="Rancho").first()
    return render_template("home.html", ListCasas = ListCasas, ListApartamentos = ListApartamentos, ListRanchos = ListRanchos, PropertyList = PropertyList)

routes/investigacion.py
from flask import Blueprint, render_template, redirect, url_for
from utils.db import db

inv = Blueprint("investigacion", __name__)


@inv.route("/investigacion")
def investigacion():
    return render_template("investigacion.html")

routes/nosotros.py
from flask import Blueprint, render_template, redirect, url_for
from utils.db import db

about = Blueprint("nosotros", __name__)


@about.route("/nosotros")
def nosotros():
    return render_template("nosotros.html")

routes/propiedad.py
from flask import Blueprint, render_template, redirect, url_for
from utils.db import db
from models.property import Property

prop = Blueprint("propiedad", __name__)


@prop.route("/propiedad/<int:id>")
def propiedad(id):
    PropertyList = Property.query.filter_by(id=id).first()
    return render_template("propiedad.html", Propiedad = PropertyList)

templates/base.html
<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href= "{{url_for('static', filename='css/style.css')}}">
        <link rel="stylesheet" href= "{{url_for('static', filename='css/Normalize.css')}}">
        <link rel="stylesheet" href= "{{url_for('static', filename='css/lightbox.css')}}">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" integrity="sha512-9usAa10IRO0HhonpyAIVpjrylPvoDwiPUiKdWk5t3PyolY1cOd4DSE0Ga+ri4AuTroPR5aQvXU9xC6qOPnzFeg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
        <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css" />
        <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
        <script type=text/javascript src="{{url_for('static', filename='js/vendor/modernizr-3.8.0.min.js')}}"></script>
        <script type=text/javascript src="{{url_for('static', filename='js/plugins.js')}}"></script>
        <script type=text/javascript src="{{url_for('static', filename='js/lightbox.js')}}"></script>
        <script type=text/javascript src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/js/all.min.js" integrity="sha512-yFjZbTYRCJodnuyGlsKamNE/LlEaEAxSUDe5+u61mV8zzqJVFOH7TnULE2/PP/l5vKWpUNnF4VGVkXh3MjgLsg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
        <script type=text/javascript src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"></script>
        <title>{% block title %}{% endblock %}</title>
        
    </head>
    <body class="nohome">
      <div class="navbar">
        <div class="logo">
          <img src="{{ url_for('static', filename='images/logo.jpg') }}" alt="">
        </div>
        <div class="nav">
          <a href="{{ url_for('home.home') }}">Home</a>
          <a href="{{ url_for('investigacion.investigacion') }}">Investigacion</a>
          <a href="{{ url_for('nosotros.nosotros') }}">Nosotros</a>
          <a href="{{ url_for('contacto.contacto') }}">Contacto</a>
        </div>
      </div>
      {% block contents %}
      {% endblock %}

      <div class="contenedor-footer">
          <footer>
            <nav class="redes-sociales">
              <p>Tel: +(503) 7844 9035</p>
              <a href="https://instagram.com/brcevallos "><i class="fab fa-instagram"></i></a>
              <a href="https://www.facebook.com/Cevallos-Bienes-Raices-107432514364803/ "><i class="fab fa-facebook-f"></i></a>
              <a href="bienesraicescevallos@gmail.com"><i class="fa-solid fa-envelope"></i></i></a>
              <p class="copyright">
              Todos Los Derechos Reservados &copy; Bienes Raices Cevallos 2022
              </p>
            </nav>
          </footer> 
      </div>  
    </body>
    
</html>

templates/basehome.html
<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href= "{{url_for('static', filename='css/style.css')}}">
        <link rel="stylesheet" href= "{{url_for('static', filename='css/Normalize.css')}}">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" integrity="sha512-9usAa10IRO0HhonpyAIVpjrylPvoDwiPUiKdWk5t3PyolY1cOd4DSE0Ga+ri4AuTroPR5aQvXU9xC6qOPnzFeg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
        <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css" />
        <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
        <script type=text/javascript src="{{url_for('static', filename='js/vendor/modernizr-3.8.0.min.js')}}"></script>
        <script type=text/javascript src="{{url_for('static', filename='js/main.js')}}"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/js/all.min.js" integrity="sha512-yFjZbTYRCJodnuyGlsKamNE/LlEaEAxSUDe5+u61mV8zzqJVFOH7TnULE2/PP/l5vKWpUNnF4VGVkXh3MjgLsg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
        <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"></script>
        <title>{% block title %}Home{% endblock %}</title>
        
    </head>
    <body class="home">
      <div class="navbar">
        <div class="logo">
          <img src="{{ url_for('static', filename='images/logo.jpg') }}" alt="">
        </div>
        <div class="nav">
          <a href="{{ url_for('home.home') }}">Home</a>
          <a href="{{ url_for('investigacion.investigacion') }}">Investigacion</a>
          <a href="{{ url_for('nosotros.nosotros') }}">Nosotros</a>
          <a href="{{ url_for('contacto.contacto') }}">Contacto</a>
        </div>
      </div>
     
      <div class="site-header"> 
        <div class="mover"></div>
       
                Encuentra tu casa ideal
      
        </div>  
      </div>
      {% block contents %}
      {% endblock %}

      <div class="contenedor-footer">
        <footer>
          <nav class="redes-sociales">
            <p>Tel: 503 78449035</p>
            <a href="https://instagram.com/brcevallos "><i class="fab fa-instagram"></i></a>
            <a href="https://www.facebook.com/Cevallos-Bienes-Raices-107432514364803/ "><i class="fab fa-facebook-f"></i></a>
            <a href="bienesraicescevallos@gmail.com"><i class="fa-solid fa-envelope"></i></i></a>
            <p class="copyright">
            Todos Los Derechos Reservados &copy; Bienes Raices Cevallos 2022
            </p>
          </nav>
        </footer> 
    </div>  
    </body>
  
</html>

templates/dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href= "{{url_for('static', filename='css/style.css')}}">
    <link rel="stylesheet" href= "{{url_for('static', filename='css/Normalize.css')}}">
    <link rel="stylesheet" href= "{{url_for('static', filename='css/lightbox.css')}}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" integrity="sha512-9usAa10IRO0HhonpyAIVpjrylPvoDwiPUiKdWk5t3PyolY1cOd4DSE0Ga+ri4AuTroPR5aQvXU9xC6qOPnzFeg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css" />
    <title>Dashboard</title>
</head>
<body>
    
    <div class="alldash">
        <br>
    <div class="envio">
        <h1>Mensajes</h1>
    </div>
    <div class="envio2">
        <table>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Message</th>
                </tr>
            </thead>
            <tbody>
                {% for Message in MessageList %}
                <tr>
                    <td>{{ Message.name }}</td>
                    <td>{{ Message.mail }}</td>
                    <td>{{ Message.message }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div> 
    <div class="alldash">
        <br>
    <div class="envio">
        <h1>Propiedades</h1>
    </div>
    <div class="envio2">
        <table>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Category</th>
                    <th>City</th>
                    <th>Size</th>
                    <th>Clasification</th>
                    <th>Price</th>
                </tr>
            </thead>
            <tbody>
                {% for Property in PropertyList %}
                <tr>
                    <td>{{ Property.name }}</td>
                    <td>{{ Property.category }}</td>
                    <td>{{ Property.city}}</td>
                    <td>{{ Property.size }}</td>
                    <td>{{ Property.clasification }}</td>
                    <td>{{ Property.price }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div> 
            <div class="centrar-b">
                <a href="{{ url_for('dashboard.property') }}" class="btn">Crear propiedad</a>
            </div>
        </div> 
    </div>
</body>
</html>

templates/home.html
{% extends 'basehome.html' %}
{% block title %}Bienes Raices Cevallos{% endblock %}
{% block contents %}

  <section class="contenedor titulo-home">
  </section>
  <h1 class="centrado primario">Propiedades</h1>
  
  <main class="contenedor mega-flex">
    
    <!--Code para filtro de busqueda-->
    <section class="filtro-cat">
      <a href="#casa" class="centrado activo">Casa</a>
      <a href="#apartamento" class="centrado">Apartamento</a>
      <a href="#rancho" class="centrado">Rancho</a>
    </section>
    <section class="filtros">
      <h3 class="centrado">Filtrar</h3>
      <div class="selectdiv">
        <label>
            <select>
                <option selected> Negocio</option>
                <option value="Alquiler">Alquiler</option>
                <option value="Venta">Venta</option>
            </select>
        </label>
      </div>
      
      <div class="selectdiv">
        <label>
            <select>
                <option selected> Seguridad</option>
                <option value="Privada">Privada</option>
                <option value="Calle principa">Calle principal</option>
                <option value="Colonia">Colonia</option>
            </select>
        </label>
      </div>

      <div class="selectdiv">
        <label>
            <select>
                <option selected> Baños</option>
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
                <option value="5">5</option>
                <option value="6">6</option>
            </select>
        </label>
      </div>

      <div class="selectdiv">
        <label>
            <select>
                <option selected> Dormitorios</option>
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
                <option value="5">5</option>
                <option value="6">6</option>
            </select>
        </label>
      </div>

      <div class="selectdiv">
        <label>
            <select>
                <option selected> Estacionamientos</option>
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
                <option value="5">5</option>
                <option value="6">6</option>
            </select>
        </label>
      </div>

    </section>

    <!--####################################           PROPIEDADES      ################################################ -->
    
    <div class="ejemplos" id="casa">
      <!--Ejemplo 1-->
    {% if ListCasas %}
    {% for Casa in ListCasas %}
      <div class="ejemplo">
        <div class="ejemplo-imagen" style="background-image: url({{ Casa.fotoperfil}}); background-size: cover; background-position: center;">
          <h3 class="precio">{{ Casa.price }} - {{ Casa.category}} </h3>
        </div>
        <div class="ejemplo-contenido">
          <h3>{{ Casa.name }}</h3>

          <ul class="iconos">
            <li class="centrado icono">
              <i class="fa-solid fa-bed"></i>
              <p>{{ Casa.dormitorios }}</p>
            </li>
            <li class="centrado icono">
              <i class="fa-solid fa-toilet"></i>
              <p>{{ Casa.banos }}</p>
            </li>
            <li class="centrado icono">
              <i class="fa-solid fa-car"></i>
              <p>{{ Casa.parqueos }}</p>
            </li>
            <li class="centrado icono">
              <i class="fa-solid fa-ruler-combined"></i>
              <p>{{ Casa.size }}</p>
            </li>
          </ul>
          <div class="centrado"> 
            <a href="{{ url_for('propiedad.propiedad', id=Casa.id) }}" class="boton boton-morado">Ver</a>

          </div>
        </div>
      </div>
      {% endfor %}
      {% endif %}
    </div>

    
    {% if ListApartamentos %}
    {% for Apartamento in ListApartamentos %}
    <div class="ejemplos" id="apartamento">
      <!--Ejemplo 1-->
      <div class="ejemplo">
        <div class="ejemplo-imagen" style="background-image: url({{ Apartamento.fotoperfil}}); background-size: cover; background-position: center;">
          <h3 class="precio">{{ Apartamento.price }} - {{ Apartamento.category}} </h3>
        </div>
        <div class="ejemplo-contenido">
          <h3>{{ Apartamento.name }}</h3>

          <ul class="iconos">
            <li class="centrado icono">
              <i class="fa-solid fa-bed"></i>
              <p>{{ Apartamento.dormitorios }}</p>
            </li>
            <li class="centrado icono">
              <i class="fa-solid fa-toilet"></i>
              <p>{{ Apartamento.banos }}</p>
            </li>
            <li class="centrado icono">
              <i class="fa-solid fa-car"></i>
              <p>{{ Apartamento.parqueos }}</p>
            </li>
            <li class="centrado icono">
              <i class="fa-solid fa-ruler-combined"></i>
              <p>{{ Apartamento.size }}</p>
            </li>
          </ul>
          <div class="centrado"> 
            <a href="{{ url_for('propiedad.propiedad', id=Apartamento.id) }}" class="boton boton-morado">Ver</a>

          </div>
        </div>
      </div>
    </div>
      {% endfor %}
    {% endif %}

    {% if ListRanchos %}
    {% for Rancho in ListRanchos %}
    <div class="ejemplos" id="rancho">
      <!--Ejemplo 1-->
      <div class="ejemplo">
        <div class="ejemplo-imagen" style="background-image: url({{ Rancho.fotoperfil}}); background-size: cover; background-position: center;">
          <h3 class="precio">{{ Rancho.price }} - {{ Rancho.category }} </h3>
        </div>
        <div class="ejemplo-contenido">
          <h3>{{ Rancho.name }}</h3>

          <ul class="iconos">
            <li class="centrado icono">
              <i class="fa-solid fa-bed"></i>
              <p>{{ Rancho.dormitorios }}</p>
            </li>
            <li class="centrado icono">
              <i class="fa-solid fa-toilet"></i>
              <p>{{ Rancho.banos }}</p>
            </li>
            <li class="centrado icono">
              <i class="fa-solid fa-car"></i>
              <p>{{ Rancho.parqueos }}</p>
            </li>
            <li class="centrado icono">
              <i class="fa-solid fa-ruler-combined"></i>
              <p>{{ Rancho.size }}</p>
            </li>
          </ul>
          <div class="centrado"> 
            <a href="{{ url_for('propiedad.propiedad', id=Rancho.id) }}" class="boton boton-morado">Ver</a>

          </div>
        </div>
      </div>
    </div>
      {% endfor %}
    {% endif %}
  </main>

  <div class="enumerador parallax">
    <div class="contenedor">
        <ul class="resumen-pa">
            <li>
                <p class="numero">50</p>Inmuebles operados</li>
            <li>
                <p class="numero">50</p>Testimonios positivos</li>
            <li>
                <p class="numero">50</p>Familias satisfechas</li>

        </ul>
    </div>
  </div>

  <!--Code de testimonios-->
  <section class="contenedor">
    <h1 class="centrado testimonio-h"> Testimonios</h1>
    <div class="testimonios">
      <div class="testimonio">
        <p class="testimonio-p">
          “Buen servicio, desde que iniciamos con el proceso de alquiler de casa, hasta que la colocaron. Fue de gran ayuda por
          la eficiencia y responsabilidad que tiene. Estoy muy satisfecha. Gracias por su trabajo. 
          La recomiendo con toda seguridad.”
          Elva de Henríquez.
        </p>
      </div>

      <div class="testimonio">
        <p class="testimonio-p">
          Agradezco a Nora Cevallos su amabilidad en mostrarnos diferentes casas en alquiler. 
          Ella es una persona dispuesta a buscar lo mejor para satisfacer a su cliente en sus necesidades de vivienda,
          no importando el tiempo e inconvenientes que esto conlleve. 
          ¡Gracias por tu ayuda, tu profesionalismo y atención en ayudarnos a encontrar lo mejor para nosotras!
          Paty Miguel y Andrea Bendeck.
        </p>
      </div>

      <div class="testimonio">
        <p class="testimonio-p">
          “La atención al cliente que Nora me dio fue excelente, especialmente porque yo vivo fuera del país.
          Aun así, Nora siempre me mantuvo informado en una manera profesional y eficiente. 
          No puedo hablar suficientemente de su profesionalismo que me hizo sentir muy fácil el progreso de principio al 
          fin”. 
          Carlos Alberto Rosales.
        </p>
      </div>

    </div>
  </section>
  <!--Code Mapa Config.-->
  <!--<section class="contendor-mapa">
    <div class="mapa-1">
      <iframe
        src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d15504.150299856461!2d-89.23720264999999!3d13.716174099999998!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1ses-419!2ssv!4v1647550072404!5m2!1ses-419!2ssv"
        width="400"
        height="300"
        style="border: 0"
        allowfullscreen=""
        loading="lazy">
      </iframe>
    </div>
  </section> -->
  <!--Code Instagram Widget-->
  <section class="contenedor instagram">
    <script src="https://apps.elfsight.com/p/platform.js" defer></script>
    <div class="elfsight-app-7aafff44-68ac-443a-a635-375252e2c5b7"></div>
  </section>
{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% block title %}login page{% endblock %}
{% block contents %}
<h1>login page</h1>
<br>
<form action="{{ url_for('auth.login') }}" method="post">
    {{ form.hidden_tag() }}
    {{ form.username.label }}
    {{ form.username }}
    {{ form.password.label }}
    {{ form.password }}
    {{ form.submit }}
</form>
<br>
<a href="{{ url_for('auth.register') }}">register</a>
{% endblock %}

templates/register.html
{% extends 'base.html' %}
{% block title %}register page{% endblock %}
{% block contents %}
<h1>register page</h1>
<br>
<form action="{{ url_for('auth.register') }}" method="post">
    {{ form.hidden_tag() }}
    {{ form.username.label }}
    {{ form.username }}
    {{ form.password.label }}
    {{ form.password }}
    {{ form.submit }}
</form>
<br>
<a href="{{ url_for('auth.login') }}">login</a>
{% endblock %}